// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: apps/room/room.proto

package room

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_apps_room_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_room_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_apps_room_room_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRoomRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type JoinRoomReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomReply) Reset() {
	*x = JoinRoomReply{}
	mi := &file_apps_room_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomReply) ProtoMessage() {}

func (x *JoinRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_room_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomReply.ProtoReflect.Descriptor instead.
func (*JoinRoomReply) Descriptor() ([]byte, []int) {
	return file_apps_room_room_proto_rawDescGZIP(), []int{1}
}

func (x *JoinRoomReply) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_apps_room_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_room_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_apps_room_room_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveRoomRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type LeaveRoomReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomReply) Reset() {
	*x = LeaveRoomReply{}
	mi := &file_apps_room_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomReply) ProtoMessage() {}

func (x *LeaveRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_room_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomReply.ProtoReflect.Descriptor instead.
func (*LeaveRoomReply) Descriptor() ([]byte, []int) {
	return file_apps_room_room_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveRoomReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayersRequest) Reset() {
	*x = GetPlayersRequest{}
	mi := &file_apps_room_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayersRequest) ProtoMessage() {}

func (x *GetPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_room_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayersRequest.ProtoReflect.Descriptor instead.
func (*GetPlayersRequest) Descriptor() ([]byte, []int) {
	return file_apps_room_room_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlayersRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetPlayersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []string               `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayersReply) Reset() {
	*x = GetPlayersReply{}
	mi := &file_apps_room_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayersReply) ProtoMessage() {}

func (x *GetPlayersReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_room_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayersReply.ProtoReflect.Descriptor instead.
func (*GetPlayersReply) Descriptor() ([]byte, []int) {
	return file_apps_room_room_proto_rawDescGZIP(), []int{5}
}

func (x *GetPlayersReply) GetPlayers() []string {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_apps_room_room_proto protoreflect.FileDescriptor

const file_apps_room_room_proto_rawDesc = "" +
	"\n" +
	"\x14apps/room/room.proto\x12\x04room\"#\n" +
	"\x0fJoinRoomRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"'\n" +
	"\rJoinRoomReply\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\"$\n" +
	"\x10LeaveRoomRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"*\n" +
	"\x0eLeaveRoomReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"+\n" +
	"\x11GetPlayersRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\"+\n" +
	"\x0fGetPlayersReply\x12\x18\n" +
	"\aplayers\x18\x01 \x03(\tR\aplayers2\xb7\x01\n" +
	"\x04Room\x126\n" +
	"\bJoinRoom\x12\x15.room.JoinRoomRequest\x1a\x13.room.JoinRoomReply\x129\n" +
	"\tLeaveRoom\x12\x16.room.LeaveRoomRequest\x1a\x14.room.LeaveRoomReply\x12<\n" +
	"\n" +
	"GetPlayers\x12\x17.room.GetPlayersRequest\x1a\x15.room.GetPlayersReplyB\bZ\x06./roomb\x06proto3"

var (
	file_apps_room_room_proto_rawDescOnce sync.Once
	file_apps_room_room_proto_rawDescData []byte
)

func file_apps_room_room_proto_rawDescGZIP() []byte {
	file_apps_room_room_proto_rawDescOnce.Do(func() {
		file_apps_room_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_room_room_proto_rawDesc), len(file_apps_room_room_proto_rawDesc)))
	})
	return file_apps_room_room_proto_rawDescData
}

var file_apps_room_room_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_apps_room_room_proto_goTypes = []any{
	(*JoinRoomRequest)(nil),   // 0: room.JoinRoomRequest
	(*JoinRoomReply)(nil),     // 1: room.JoinRoomReply
	(*LeaveRoomRequest)(nil),  // 2: room.LeaveRoomRequest
	(*LeaveRoomReply)(nil),    // 3: room.LeaveRoomReply
	(*GetPlayersRequest)(nil), // 4: room.GetPlayersRequest
	(*GetPlayersReply)(nil),   // 5: room.GetPlayersReply
}
var file_apps_room_room_proto_depIdxs = []int32{
	0, // 0: room.Room.JoinRoom:input_type -> room.JoinRoomRequest
	2, // 1: room.Room.LeaveRoom:input_type -> room.LeaveRoomRequest
	4, // 2: room.Room.GetPlayers:input_type -> room.GetPlayersRequest
	1, // 3: room.Room.JoinRoom:output_type -> room.JoinRoomReply
	3, // 4: room.Room.LeaveRoom:output_type -> room.LeaveRoomReply
	5, // 5: room.Room.GetPlayers:output_type -> room.GetPlayersReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_room_room_proto_init() }
func file_apps_room_room_proto_init() {
	if File_apps_room_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_room_room_proto_rawDesc), len(file_apps_room_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_room_room_proto_goTypes,
		DependencyIndexes: file_apps_room_room_proto_depIdxs,
		MessageInfos:      file_apps_room_room_proto_msgTypes,
	}.Build()
	File_apps_room_room_proto = out.File
	file_apps_room_room_proto_goTypes = nil
	file_apps_room_room_proto_depIdxs = nil
}
