// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type ProfileReq struct {
	Uid int64 `json:"uid"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserReply struct {
	Uid      int64  `json:"uid"`
	Token    string `json:"token"`
	Coins    int64  `json:"coins,omitempty"`
	Username string `json:"username,omitempty"`
}
