// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: room.proto

package server

import (
	"context"

	"fish-game/apps/room/internal/logic/room"
	"fish-game/apps/room/internal/svc"
	"fish-game/apps/room/room"
)

type RoomServer struct {
	svcCtx *svc.ServiceContext
	room.UnimplementedRoomServer
}

func NewRoomServer(svcCtx *svc.ServiceContext) *RoomServer {
	return &RoomServer{
		svcCtx: svcCtx,
	}
}

func (s *RoomServer) JoinRoom(ctx context.Context, in *room.JoinRoomRequest) (*room.JoinRoomReply, error) {
	l := roomlogic.NewJoinRoomLogic(ctx, s.svcCtx)
	return l.JoinRoom(in)
}

func (s *RoomServer) LeaveRoom(ctx context.Context, in *room.LeaveRoomRequest) (*room.LeaveRoomReply, error) {
	l := roomlogic.NewLeaveRoomLogic(ctx, s.svcCtx)
	return l.LeaveRoom(in)
}

func (s *RoomServer) GetPlayers(ctx context.Context, in *room.GetPlayersRequest) (*room.GetPlayersReply, error) {
	l := roomlogic.NewGetPlayersLogic(ctx, s.svcCtx)
	return l.GetPlayers(in)
}
