// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user.proto

package server

import (
	"context"

	"fish-game/apps/user/internal/logic/user"
	"fish-game/apps/user/internal/svc"
	"fish-game/apps/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := userlogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *user.LoginRequest) (*user.LoginResponse, error) {
	l := userlogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) GetProfile(ctx context.Context, in *user.ProfileRequest) (*user.ProfileResponse, error) {
	l := userlogic.NewGetProfileLogic(ctx, s.svcCtx)
	return l.GetProfile(in)
}

func (s *UserServer) AddGold(ctx context.Context, in *user.AddGoldRequest) (*user.AddGoldResponse, error) {
	l := userlogic.NewAddGoldLogic(ctx, s.svcCtx)
	return l.AddGold(in)
}
