// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: proto/skill.proto

package ws

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SkillCooldown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SkillType     string                 `protobuf:"bytes,2,opt,name=skill_type,json=skillType,proto3" json:"skill_type,omitempty"`
	DurationSec   int32                  `protobuf:"varint,3,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillCooldown) Reset() {
	*x = SkillCooldown{}
	mi := &file_proto_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillCooldown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillCooldown) ProtoMessage() {}

func (x *SkillCooldown) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillCooldown.ProtoReflect.Descriptor instead.
func (*SkillCooldown) Descriptor() ([]byte, []int) {
	return file_proto_skill_proto_rawDescGZIP(), []int{0}
}

func (x *SkillCooldown) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SkillCooldown) GetSkillType() string {
	if x != nil {
		return x.SkillType
	}
	return ""
}

func (x *SkillCooldown) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

var File_proto_skill_proto protoreflect.FileDescriptor

const file_proto_skill_proto_rawDesc = "" +
	"\n" +
	"\x11proto/skill.proto\x12\x02ws\"j\n" +
	"\rSkillCooldown\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"skill_type\x18\x02 \x01(\tR\tskillType\x12!\n" +
	"\fduration_sec\x18\x03 \x01(\x05R\vdurationSecB\x11Z\x0ffish-game/ws;wsb\x06proto3"

var (
	file_proto_skill_proto_rawDescOnce sync.Once
	file_proto_skill_proto_rawDescData []byte
)

func file_proto_skill_proto_rawDescGZIP() []byte {
	file_proto_skill_proto_rawDescOnce.Do(func() {
		file_proto_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_skill_proto_rawDesc), len(file_proto_skill_proto_rawDesc)))
	})
	return file_proto_skill_proto_rawDescData
}

var file_proto_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_skill_proto_goTypes = []any{
	(*SkillCooldown)(nil), // 0: ws.SkillCooldown
}
var file_proto_skill_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_skill_proto_init() }
func file_proto_skill_proto_init() {
	if File_proto_skill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_skill_proto_rawDesc), len(file_proto_skill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_skill_proto_goTypes,
		DependencyIndexes: file_proto_skill_proto_depIdxs,
		MessageInfos:      file_proto_skill_proto_msgTypes,
	}.Build()
	File_proto_skill_proto = out.File
	file_proto_skill_proto_goTypes = nil
	file_proto_skill_proto_depIdxs = nil
}
