// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: proto/ws.proto

package ws

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WSMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSMessage) Reset() {
	*x = WSMessage{}
	mi := &file_proto_ws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSMessage) ProtoMessage() {}

func (x *WSMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSMessage.ProtoReflect.Descriptor instead.
func (*WSMessage) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{0}
}

func (x *WSMessage) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *WSMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ShootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BulletId      int32                  `protobuf:"varint,1,opt,name=bullet_id,json=bulletId,proto3" json:"bullet_id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShootRequest) Reset() {
	*x = ShootRequest{}
	mi := &file_proto_ws_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootRequest) ProtoMessage() {}

func (x *ShootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootRequest.ProtoReflect.Descriptor instead.
func (*ShootRequest) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{1}
}

func (x *ShootRequest) GetBulletId() int32 {
	if x != nil {
		return x.BulletId
	}
	return 0
}

func (x *ShootRequest) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ShootRequest) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type FishGenerate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FishGenerate) Reset() {
	*x = FishGenerate{}
	mi := &file_proto_ws_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FishGenerate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FishGenerate) ProtoMessage() {}

func (x *FishGenerate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FishGenerate.ProtoReflect.Descriptor instead.
func (*FishGenerate) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{2}
}

func (x *FishGenerate) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FishGenerate) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *FishGenerate) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type FishKilled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FishId        int32                  `protobuf:"varint,1,opt,name=fish_id,json=fishId,proto3" json:"fish_id,omitempty"`
	ByUserId      int32                  `protobuf:"varint,2,opt,name=by_user_id,json=byUserId,proto3" json:"by_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FishKilled) Reset() {
	*x = FishKilled{}
	mi := &file_proto_ws_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FishKilled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FishKilled) ProtoMessage() {}

func (x *FishKilled) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FishKilled.ProtoReflect.Descriptor instead.
func (*FishKilled) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{3}
}

func (x *FishKilled) GetFishId() int32 {
	if x != nil {
		return x.FishId
	}
	return 0
}

func (x *FishKilled) GetByUserId() int32 {
	if x != nil {
		return x.ByUserId
	}
	return 0
}

type CoinUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Coins         int32                  `protobuf:"varint,2,opt,name=coins,proto3" json:"coins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoinUpdate) Reset() {
	*x = CoinUpdate{}
	mi := &file_proto_ws_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinUpdate) ProtoMessage() {}

func (x *CoinUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinUpdate.ProtoReflect.Descriptor instead.
func (*CoinUpdate) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{4}
}

func (x *CoinUpdate) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CoinUpdate) GetCoins() int32 {
	if x != nil {
		return x.Coins
	}
	return 0
}

var File_proto_ws_proto protoreflect.FileDescriptor

const file_proto_ws_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ws.proto\x12\x02ws\"5\n" +
	"\tWSMessage\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"G\n" +
	"\fShootRequest\x12\x1b\n" +
	"\tbullet_id\x18\x01 \x01(\x05R\bbulletId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\":\n" +
	"\fFishGenerate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\"C\n" +
	"\n" +
	"FishKilled\x12\x17\n" +
	"\afish_id\x18\x01 \x01(\x05R\x06fishId\x12\x1c\n" +
	"\n" +
	"by_user_id\x18\x02 \x01(\x05R\bbyUserId\";\n" +
	"\n" +
	"CoinUpdate\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05coins\x18\x02 \x01(\x05R\x05coinsB\x11Z\x0ffish-game/ws;wsb\x06proto3"

var (
	file_proto_ws_proto_rawDescOnce sync.Once
	file_proto_ws_proto_rawDescData []byte
)

func file_proto_ws_proto_rawDescGZIP() []byte {
	file_proto_ws_proto_rawDescOnce.Do(func() {
		file_proto_ws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ws_proto_rawDesc), len(file_proto_ws_proto_rawDesc)))
	})
	return file_proto_ws_proto_rawDescData
}

var file_proto_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_ws_proto_goTypes = []any{
	(*WSMessage)(nil),    // 0: ws.WSMessage
	(*ShootRequest)(nil), // 1: ws.ShootRequest
	(*FishGenerate)(nil), // 2: ws.FishGenerate
	(*FishKilled)(nil),   // 3: ws.FishKilled
	(*CoinUpdate)(nil),   // 4: ws.CoinUpdate
}
var file_proto_ws_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ws_proto_init() }
func file_proto_ws_proto_init() {
	if File_proto_ws_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ws_proto_rawDesc), len(file_proto_ws_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ws_proto_goTypes,
		DependencyIndexes: file_proto_ws_proto_depIdxs,
		MessageInfos:      file_proto_ws_proto_msgTypes,
	}.Build()
	File_proto_ws_proto = out.File
	file_proto_ws_proto_goTypes = nil
	file_proto_ws_proto_depIdxs = nil
}
