// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: proto/ws.proto

package ws

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WSMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSMessage) Reset() {
	*x = WSMessage{}
	mi := &file_proto_ws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSMessage) ProtoMessage() {}

func (x *WSMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSMessage.ProtoReflect.Descriptor instead.
func (*WSMessage) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{0}
}

func (x *WSMessage) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *WSMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ShootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BulletId      int32                  `protobuf:"varint,1,opt,name=bullet_id,json=bulletId,proto3" json:"bullet_id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShootRequest) Reset() {
	*x = ShootRequest{}
	mi := &file_proto_ws_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootRequest) ProtoMessage() {}

func (x *ShootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootRequest.ProtoReflect.Descriptor instead.
func (*ShootRequest) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{1}
}

func (x *ShootRequest) GetBulletId() int32 {
	if x != nil {
		return x.BulletId
	}
	return 0
}

func (x *ShootRequest) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ShootRequest) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type FishGenerate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FishGenerate) Reset() {
	*x = FishGenerate{}
	mi := &file_proto_ws_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FishGenerate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FishGenerate) ProtoMessage() {}

func (x *FishGenerate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FishGenerate.ProtoReflect.Descriptor instead.
func (*FishGenerate) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{2}
}

func (x *FishGenerate) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FishGenerate) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *FishGenerate) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type FishKilled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FishId        int32                  `protobuf:"varint,1,opt,name=fish_id,json=fishId,proto3" json:"fish_id,omitempty"`
	ByUserId      int32                  `protobuf:"varint,2,opt,name=by_user_id,json=byUserId,proto3" json:"by_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FishKilled) Reset() {
	*x = FishKilled{}
	mi := &file_proto_ws_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FishKilled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FishKilled) ProtoMessage() {}

func (x *FishKilled) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FishKilled.ProtoReflect.Descriptor instead.
func (*FishKilled) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{3}
}

func (x *FishKilled) GetFishId() int32 {
	if x != nil {
		return x.FishId
	}
	return 0
}

func (x *FishKilled) GetByUserId() int32 {
	if x != nil {
		return x.ByUserId
	}
	return 0
}

type CoinUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Coins         int32                  `protobuf:"varint,2,opt,name=coins,proto3" json:"coins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoinUpdate) Reset() {
	*x = CoinUpdate{}
	mi := &file_proto_ws_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinUpdate) ProtoMessage() {}

func (x *CoinUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinUpdate.ProtoReflect.Descriptor instead.
func (*CoinUpdate) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{4}
}

func (x *CoinUpdate) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CoinUpdate) GetCoins() int32 {
	if x != nil {
		return x.Coins
	}
	return 0
}

type GoldUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Gold          int32                  `protobuf:"varint,2,opt,name=gold,proto3" json:"gold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoldUpdate) Reset() {
	*x = GoldUpdate{}
	mi := &file_proto_ws_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoldUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoldUpdate) ProtoMessage() {}

func (x *GoldUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoldUpdate.ProtoReflect.Descriptor instead.
func (*GoldUpdate) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{5}
}

func (x *GoldUpdate) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GoldUpdate) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

type FishPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FishPosition) Reset() {
	*x = FishPosition{}
	mi := &file_proto_ws_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FishPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FishPosition) ProtoMessage() {}

func (x *FishPosition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FishPosition.ProtoReflect.Descriptor instead.
func (*FishPosition) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{6}
}

func (x *FishPosition) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FishPosition) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *FishPosition) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type FishPositionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*FishPosition        `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FishPositionUpdate) Reset() {
	*x = FishPositionUpdate{}
	mi := &file_proto_ws_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FishPositionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FishPositionUpdate) ProtoMessage() {}

func (x *FishPositionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FishPositionUpdate.ProtoReflect.Descriptor instead.
func (*FishPositionUpdate) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{7}
}

func (x *FishPositionUpdate) GetPositions() []*FishPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

type UseSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SkillType     string                 `protobuf:"bytes,2,opt,name=skill_type,json=skillType,proto3" json:"skill_type,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"` // 坐标（可选）
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseSkillRequest) Reset() {
	*x = UseSkillRequest{}
	mi := &file_proto_ws_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseSkillRequest) ProtoMessage() {}

func (x *UseSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseSkillRequest.ProtoReflect.Descriptor instead.
func (*UseSkillRequest) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{8}
}

func (x *UseSkillRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UseSkillRequest) GetSkillType() string {
	if x != nil {
		return x.SkillType
	}
	return ""
}

func (x *UseSkillRequest) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *UseSkillRequest) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SkillUsed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SkillType     string                 `protobuf:"bytes,2,opt,name=skill_type,json=skillType,proto3" json:"skill_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillUsed) Reset() {
	*x = SkillUsed{}
	mi := &file_proto_ws_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillUsed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillUsed) ProtoMessage() {}

func (x *SkillUsed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillUsed.ProtoReflect.Descriptor instead.
func (*SkillUsed) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{9}
}

func (x *SkillUsed) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SkillUsed) GetSkillType() string {
	if x != nil {
		return x.SkillType
	}
	return ""
}

type FishFreeze struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DurationMs    int32                  `protobuf:"varint,1,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // 冻结持续时间（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FishFreeze) Reset() {
	*x = FishFreeze{}
	mi := &file_proto_ws_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FishFreeze) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FishFreeze) ProtoMessage() {}

func (x *FishFreeze) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FishFreeze.ProtoReflect.Descriptor instead.
func (*FishFreeze) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{10}
}

func (x *FishFreeze) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type FishLocked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FishId        int32                  `protobuf:"varint,2,opt,name=fish_id,json=fishId,proto3" json:"fish_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FishLocked) Reset() {
	*x = FishLocked{}
	mi := &file_proto_ws_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FishLocked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FishLocked) ProtoMessage() {}

func (x *FishLocked) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FishLocked.ProtoReflect.Descriptor instead.
func (*FishLocked) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{11}
}

func (x *FishLocked) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FishLocked) GetFishId() int32 {
	if x != nil {
		return x.FishId
	}
	return 0
}

type SpeedUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Duration      int32                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeedUp) Reset() {
	*x = SpeedUp{}
	mi := &file_proto_ws_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedUp) ProtoMessage() {}

func (x *SpeedUp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedUp.ProtoReflect.Descriptor instead.
func (*SpeedUp) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{12}
}

func (x *SpeedUp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SpeedUp) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type RadarResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CenterX       float32                `protobuf:"fixed32,2,opt,name=centerX,proto3" json:"centerX,omitempty"`
	CenterY       float32                `protobuf:"fixed32,3,opt,name=centerY,proto3" json:"centerY,omitempty"`
	Radius        float32                `protobuf:"fixed32,4,opt,name=radius,proto3" json:"radius,omitempty"`
	FishFound     []*FishPosition        `protobuf:"bytes,5,rep,name=fish_found,json=fishFound,proto3" json:"fish_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RadarResult) Reset() {
	*x = RadarResult{}
	mi := &file_proto_ws_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadarResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadarResult) ProtoMessage() {}

func (x *RadarResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadarResult.ProtoReflect.Descriptor instead.
func (*RadarResult) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{13}
}

func (x *RadarResult) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RadarResult) GetCenterX() float32 {
	if x != nil {
		return x.CenterX
	}
	return 0
}

func (x *RadarResult) GetCenterY() float32 {
	if x != nil {
		return x.CenterY
	}
	return 0
}

func (x *RadarResult) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *RadarResult) GetFishFound() []*FishPosition {
	if x != nil {
		return x.FishFound
	}
	return nil
}

type AreaSlowDown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CenterX       float32                `protobuf:"fixed32,1,opt,name=centerX,proto3" json:"centerX,omitempty"`
	CenterY       float32                `protobuf:"fixed32,2,opt,name=centerY,proto3" json:"centerY,omitempty"`
	Radius        float32                `protobuf:"fixed32,3,opt,name=radius,proto3" json:"radius,omitempty"`
	Duration      int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"` // 秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AreaSlowDown) Reset() {
	*x = AreaSlowDown{}
	mi := &file_proto_ws_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AreaSlowDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaSlowDown) ProtoMessage() {}

func (x *AreaSlowDown) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaSlowDown.ProtoReflect.Descriptor instead.
func (*AreaSlowDown) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{14}
}

func (x *AreaSlowDown) GetCenterX() float32 {
	if x != nil {
		return x.CenterX
	}
	return 0
}

func (x *AreaSlowDown) GetCenterY() float32 {
	if x != nil {
		return x.CenterY
	}
	return 0
}

func (x *AreaSlowDown) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *AreaSlowDown) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type MagnetEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CenterX       float32                `protobuf:"fixed32,2,opt,name=center_x,json=centerX,proto3" json:"center_x,omitempty"`
	CenterY       float32                `protobuf:"fixed32,3,opt,name=center_y,json=centerY,proto3" json:"center_y,omitempty"`
	Radius        float32                `protobuf:"fixed32,4,opt,name=radius,proto3" json:"radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MagnetEffect) Reset() {
	*x = MagnetEffect{}
	mi := &file_proto_ws_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MagnetEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MagnetEffect) ProtoMessage() {}

func (x *MagnetEffect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MagnetEffect.ProtoReflect.Descriptor instead.
func (*MagnetEffect) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{15}
}

func (x *MagnetEffect) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MagnetEffect) GetCenterX() float32 {
	if x != nil {
		return x.CenterX
	}
	return 0
}

func (x *MagnetEffect) GetCenterY() float32 {
	if x != nil {
		return x.CenterY
	}
	return 0
}

func (x *MagnetEffect) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

type EMPBlastEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CenterX       float32                `protobuf:"fixed32,2,opt,name=center_x,json=centerX,proto3" json:"center_x,omitempty"`
	CenterY       float32                `protobuf:"fixed32,3,opt,name=center_y,json=centerY,proto3" json:"center_y,omitempty"`
	Radius        float32                `protobuf:"fixed32,4,opt,name=radius,proto3" json:"radius,omitempty"`
	Duration      int32                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"` // 秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EMPBlastEffect) Reset() {
	*x = EMPBlastEffect{}
	mi := &file_proto_ws_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EMPBlastEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EMPBlastEffect) ProtoMessage() {}

func (x *EMPBlastEffect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EMPBlastEffect.ProtoReflect.Descriptor instead.
func (*EMPBlastEffect) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{16}
}

func (x *EMPBlastEffect) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EMPBlastEffect) GetCenterX() float32 {
	if x != nil {
		return x.CenterX
	}
	return 0
}

func (x *EMPBlastEffect) GetCenterY() float32 {
	if x != nil {
		return x.CenterY
	}
	return 0
}

func (x *EMPBlastEffect) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *EMPBlastEffect) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type Invisibility struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Duration      int32                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"` // 秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invisibility) Reset() {
	*x = Invisibility{}
	mi := &file_proto_ws_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invisibility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invisibility) ProtoMessage() {}

func (x *Invisibility) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invisibility.ProtoReflect.Descriptor instead.
func (*Invisibility) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{17}
}

func (x *Invisibility) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Invisibility) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type FishGrowEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CenterX       float32                `protobuf:"fixed32,2,opt,name=center_x,json=centerX,proto3" json:"center_x,omitempty"`
	CenterY       float32                `protobuf:"fixed32,3,opt,name=center_y,json=centerY,proto3" json:"center_y,omitempty"`
	Radius        float32                `protobuf:"fixed32,4,opt,name=radius,proto3" json:"radius,omitempty"`
	Scale         float32                `protobuf:"fixed32,5,opt,name=scale,proto3" json:"scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FishGrowEffect) Reset() {
	*x = FishGrowEffect{}
	mi := &file_proto_ws_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FishGrowEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FishGrowEffect) ProtoMessage() {}

func (x *FishGrowEffect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FishGrowEffect.ProtoReflect.Descriptor instead.
func (*FishGrowEffect) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{18}
}

func (x *FishGrowEffect) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FishGrowEffect) GetCenterX() float32 {
	if x != nil {
		return x.CenterX
	}
	return 0
}

func (x *FishGrowEffect) GetCenterY() float32 {
	if x != nil {
		return x.CenterY
	}
	return 0
}

func (x *FishGrowEffect) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *FishGrowEffect) GetScale() float32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

var File_proto_ws_proto protoreflect.FileDescriptor

const file_proto_ws_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ws.proto\x12\x02ws\"5\n" +
	"\tWSMessage\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"G\n" +
	"\fShootRequest\x12\x1b\n" +
	"\tbullet_id\x18\x01 \x01(\x05R\bbulletId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\":\n" +
	"\fFishGenerate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\"C\n" +
	"\n" +
	"FishKilled\x12\x17\n" +
	"\afish_id\x18\x01 \x01(\x05R\x06fishId\x12\x1c\n" +
	"\n" +
	"by_user_id\x18\x02 \x01(\x05R\bbyUserId\";\n" +
	"\n" +
	"CoinUpdate\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05coins\x18\x02 \x01(\x05R\x05coins\"9\n" +
	"\n" +
	"GoldUpdate\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04gold\x18\x02 \x01(\x05R\x04gold\":\n" +
	"\fFishPosition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\"D\n" +
	"\x12FishPositionUpdate\x12.\n" +
	"\tpositions\x18\x01 \x03(\v2\x10.ws.FishPositionR\tpositions\"e\n" +
	"\x0fUseSkillRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"skill_type\x18\x02 \x01(\tR\tskillType\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\"C\n" +
	"\tSkillUsed\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"skill_type\x18\x02 \x01(\tR\tskillType\"-\n" +
	"\n" +
	"FishFreeze\x12\x1f\n" +
	"\vduration_ms\x18\x01 \x01(\x05R\n" +
	"durationMs\">\n" +
	"\n" +
	"FishLocked\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\afish_id\x18\x02 \x01(\x05R\x06fishId\">\n" +
	"\aSpeedUp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x05R\bduration\"\xa3\x01\n" +
	"\vRadarResult\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\acenterX\x18\x02 \x01(\x02R\acenterX\x12\x18\n" +
	"\acenterY\x18\x03 \x01(\x02R\acenterY\x12\x16\n" +
	"\x06radius\x18\x04 \x01(\x02R\x06radius\x12/\n" +
	"\n" +
	"fish_found\x18\x05 \x03(\v2\x10.ws.FishPositionR\tfishFound\"v\n" +
	"\fAreaSlowDown\x12\x18\n" +
	"\acenterX\x18\x01 \x01(\x02R\acenterX\x12\x18\n" +
	"\acenterY\x18\x02 \x01(\x02R\acenterY\x12\x16\n" +
	"\x06radius\x18\x03 \x01(\x02R\x06radius\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\"u\n" +
	"\fMagnetEffect\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bcenter_x\x18\x02 \x01(\x02R\acenterX\x12\x19\n" +
	"\bcenter_y\x18\x03 \x01(\x02R\acenterY\x12\x16\n" +
	"\x06radius\x18\x04 \x01(\x02R\x06radius\"\x93\x01\n" +
	"\x0eEMPBlastEffect\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bcenter_x\x18\x02 \x01(\x02R\acenterX\x12\x19\n" +
	"\bcenter_y\x18\x03 \x01(\x02R\acenterY\x12\x16\n" +
	"\x06radius\x18\x04 \x01(\x02R\x06radius\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration\"C\n" +
	"\fInvisibility\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x05R\bduration\"\x8d\x01\n" +
	"\x0eFishGrowEffect\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bcenter_x\x18\x02 \x01(\x02R\acenterX\x12\x19\n" +
	"\bcenter_y\x18\x03 \x01(\x02R\acenterY\x12\x16\n" +
	"\x06radius\x18\x04 \x01(\x02R\x06radius\x12\x14\n" +
	"\x05scale\x18\x05 \x01(\x02R\x05scaleB\x11Z\x0ffish-game/ws;wsb\x06proto3"

var (
	file_proto_ws_proto_rawDescOnce sync.Once
	file_proto_ws_proto_rawDescData []byte
)

func file_proto_ws_proto_rawDescGZIP() []byte {
	file_proto_ws_proto_rawDescOnce.Do(func() {
		file_proto_ws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ws_proto_rawDesc), len(file_proto_ws_proto_rawDesc)))
	})
	return file_proto_ws_proto_rawDescData
}

var file_proto_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_ws_proto_goTypes = []any{
	(*WSMessage)(nil),          // 0: ws.WSMessage
	(*ShootRequest)(nil),       // 1: ws.ShootRequest
	(*FishGenerate)(nil),       // 2: ws.FishGenerate
	(*FishKilled)(nil),         // 3: ws.FishKilled
	(*CoinUpdate)(nil),         // 4: ws.CoinUpdate
	(*GoldUpdate)(nil),         // 5: ws.GoldUpdate
	(*FishPosition)(nil),       // 6: ws.FishPosition
	(*FishPositionUpdate)(nil), // 7: ws.FishPositionUpdate
	(*UseSkillRequest)(nil),    // 8: ws.UseSkillRequest
	(*SkillUsed)(nil),          // 9: ws.SkillUsed
	(*FishFreeze)(nil),         // 10: ws.FishFreeze
	(*FishLocked)(nil),         // 11: ws.FishLocked
	(*SpeedUp)(nil),            // 12: ws.SpeedUp
	(*RadarResult)(nil),        // 13: ws.RadarResult
	(*AreaSlowDown)(nil),       // 14: ws.AreaSlowDown
	(*MagnetEffect)(nil),       // 15: ws.MagnetEffect
	(*EMPBlastEffect)(nil),     // 16: ws.EMPBlastEffect
	(*Invisibility)(nil),       // 17: ws.Invisibility
	(*FishGrowEffect)(nil),     // 18: ws.FishGrowEffect
}
var file_proto_ws_proto_depIdxs = []int32{
	6, // 0: ws.FishPositionUpdate.positions:type_name -> ws.FishPosition
	6, // 1: ws.RadarResult.fish_found:type_name -> ws.FishPosition
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ws_proto_init() }
func file_proto_ws_proto_init() {
	if File_proto_ws_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ws_proto_rawDesc), len(file_proto_ws_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ws_proto_goTypes,
		DependencyIndexes: file_proto_ws_proto_depIdxs,
		MessageInfos:      file_proto_ws_proto_msgTypes,
	}.Build()
	File_proto_ws_proto = out.File
	file_proto_ws_proto_goTypes = nil
	file_proto_ws_proto_depIdxs = nil
}
